const PROJECTS = [
	{
		name: 'Instant Messaging App',
		link: 'https://messaging-app.up.railway.app',
		repo: 'https://github.com/riyadh-dev/messaging-app',
		thumbnail: './images/messaging-app/4.png',
		images: [
			'./images/messaging-app/1.png',
			'./images/messaging-app/2.png',
			'./images/messaging-app/3.png',
			'./images/messaging-app/4.png',
			'./images/messaging-app/5.png',
			'./images/messaging-app/6.png',
		],
	},
	{
		name: 'Social Media App',
		link: 'https://social-media-app-production.up.railway.app',
		repo: 'https://github.com/riyadh-dev/social-media-app',
		thumbnail: './images/social-media-app/3.png',
		images: [
			'./images/social-media-app/1.png',
			'./images/social-media-app/2.png',
			'./images/social-media-app/3.png',
			'./images/social-media-app/4.png',
			'./images/social-media-app/5.png',
			'./images/social-media-app/6.png',
			'./images/social-media-app/7.png',
			'./images/social-media-app/8.png',
			'./images/social-media-app/9.png',
			'./images/social-media-app/10.png',
		],
	},
	{
		name: 'Scientific Consul Management System',
		link: 'https://scms-client.netlify.app/',
		repo: 'https://github.com/riyadh-dev/scms-client',
		thumbnail: './images/scms/5.png',
		images: [
			'./images/scms/1.png',
			'./images/scms/2.png',
			'./images/scms/3.png',
			'./images/scms/4.png',
			'./images/scms/5.png',
			'./images/scms/6.png',
			'./images/scms/7.png',
			'./images/scms/8.png',
			'./images/scms/9.png',
			'./images/scms/10.png',
			'./images/scms/11.png',
			'./images/scms/12.png',
			'./images/scms/13.png',
		],
	},
	{
		name: 'Card Matching Game',
		link: 'https://riyadh-dev-memory-matching-game.netlify.app/',
		repo: 'https://github.com/riyadh-dev/memory-matching-game',
		thumbnail: './images/memory-matching-game/1.png',
		images: ['./images/memory-matching-game/1.png'],
	},
	{
		name: 'Authentication Demo',
		link: 'https://authentication-demo.up.railway.app/',
		repo: 'https://github.com/riyadh-dev/authentication-demo',
		thumbnail: './images/authentication-demo/2.png',
		images: [
			'./images/authentication-demo/1.png',
			'./images/authentication-demo/2.png',
			'./images/authentication-demo/3.png',
			'./images/authentication-demo/4.png',
			'./images/authentication-demo/5.png',
		],
	},
	{
		name: 'IEC101 Master Sim',
		link: 'https://github.com/riyadh-dev/iec101-master-sim/releases/download/v1.0.0/IEC101MasterSim.exe',
		repo: 'https://github.com/riyadh-dev/iec101-master-sim',
		thumbnail: './images/iec101-master-sim/2.png',
		images: [
			'./images/iec101-master-sim/1.png',
			'./images/iec101-master-sim/2.png',
		],
	},
	{
		name: 'Portfolio Website (React JS)',
		link: '',
		repo: '',
		thumbnail: './images/portfolio-website-image/1.png',
		images: [
			'./images/portfolio-website-image/1.png',
			'./images/portfolio-website-image/2.png',
			'./images/portfolio-website-image/3.png',
			'./images/portfolio-website-image/4.png',
			'./images/portfolio-website-image/5.png',
			'./images/portfolio-website-image/6.png',
		],
	},
	{
		name: 'Portfolio Website (No Framework)',
		link: 'https://riyadh-dev.github.io/portfolio-website',
		repo: 'https://github.com/riyadh-dev/portfolio-website',
		thumbnail: './images/portfolio-website-image/3.png',
		images: [
			'./images/portfolio-website-image/1.png',
			'./images/portfolio-website-image/2.png',
			'./images/portfolio-website-image/3.png',
			'./images/portfolio-website-image/4.png',
			'./images/portfolio-website-image/5.png',
			'./images/portfolio-website-image/6.png',
		],
	},
];

export default PROJECTS;
